export async function fetchProducts() {
    return [
        // === CPU ===
        {
            id: 1,
            title: 'Intel Core i3-12100F',
            category: 'CPU',
            brand: 'Intel',
            price: 399,
            image: './src/img/cpu/intel-i3-12100f.jpg',
        },
        {
            id: 2,
            title: 'Intel Core i5-12400F',
            category: 'CPU',
            brand: 'Intel',
            price: 699,
            image: './src/img/cpu/intel-i5-12400f.jpg',
        },
        {
            id: 3,
            title: 'Intel Core i7-12700K',
            category: 'CPU',
            brand: 'Intel',
            price: 1499,
            image: './src/img/cpu/intel-i7-12700k.jpg',
        },
        {
            id: 4,
            title: 'Intel Core i9-13900K',
            category: 'CPU',
            brand: 'Intel',
            price: 2899,
            image: './src/img/cpu/intel-i9-13900k.jpg',
        },
        {
            id: 5,
            title: 'AMD Ryzen 5 5600',
            category: 'CPU',
            brand: 'AMD',
            price: 499,
            image: './src/img/cpu/amd-ryzen5-5600.jpg',
        },
        {
            id: 6,
            title: 'AMD Ryzen 7 5800X',
            category: 'CPU',
            brand: 'AMD',
            price: 1199,
            image: './src/img/cpu/amd-ryzen7-5800x.jpg',
        },
        {
            id: 7,
            title: 'AMD Ryzen 9 5900X',
            category: 'CPU',
            brand: 'AMD',
            price: 1799,
            image: './src/img/cpu/amd-ryzen9-5900x.jpg',
        },
        {
            id: 8,
            title: 'AMD Ryzen 9 7950X',
            category: 'CPU',
            brand: 'AMD',
            price: 2999,
            image: './src/img/cpu/amd-ryzen9-7950x.jpg',
        },
        {
            id: 9,
            title: 'Intel Pentium Gold G7400',
            category: 'CPU',
            brand: 'Intel',
            price: 249,
            image: './src/img/cpu/intel-pentium-g7400.jpg',
        },
        {
            id: 10,
            title: 'AMD Athlon 3000G',
            category: 'CPU',
            brand: 'AMD',
            price: 199,
            image: './src/img/cpu/amd-athlon-3000g.jpg',
        },

        // === GPU ===
        {
            id: 11,
            title: 'NVIDIA GTX 1650',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 899,
            image: './src/img/gpu/nvidia-gtx1650.jpg',
        },
        {
            id: 12,
            title: 'NVIDIA RTX 3050',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 1299,
            image: './src/img/gpu/nvidia-rtx3050.jpg',
        },
        {
            id: 13,
            title: 'NVIDIA RTX 3060',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 1599,
            image: './src/img/gpu/nvidia-rtx3060.jpg',
        },
        {
            id: 14,
            title: 'NVIDIA RTX 3070',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 2399,
            image: './src/img/gpu/nvidia-rtx3070.jpg',
        },
        {
            id: 15,
            title: 'NVIDIA RTX 3080',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 3299,
            image: './src/img/gpu/nvidia-rtx3080.jpg',
        },
        {
            id: 16,
            title: 'NVIDIA RTX 4090',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 7999,
            image: './src/img/gpu/nvidia-rtx4090.jpg',
        },
        {
            id: 17,
            title: 'AMD Radeon RX 6600',
            category: 'GPU',
            brand: 'AMD',
            price: 1299,
            image: './src/img/gpu/amd-rx6600.jpg',
        },
        {
            id: 18,
            title: 'AMD Radeon RX 6700 XT',
            category: 'GPU',
            brand: 'AMD',
            price: 1899,
            image: './src/img/gpu/amd-rx6700xt.jpg',
        },
        {
            id: 19,
            title: 'AMD Radeon RX 6800',
            category: 'GPU',
            brand: 'AMD',
            price: 2499,
            image: './src/img/gpu/amd-rx6800.jpg',
        },
        {
            id: 20,
            title: 'AMD Radeon RX 7900 XTX',
            category: 'GPU',
            brand: 'AMD',
            price: 4999,
            image: './src/img/gpu/amd-rx7900xtx.jpg',
        },

        // === RAM ===
        {
            id: 21,
            title: 'Corsair Vengeance 8GB DDR4',
            category: 'RAM',
            brand: 'Corsair',
            price: 129,
            image: './src/img/ram/corsair-8gb.jpg',
        },
        {
            id: 22,
            title: 'Corsair Vengeance 16GB DDR4',
            category: 'RAM',
            brand: 'Corsair',
            price: 229,
            image: './src/img/ram/corsair-16gb.jpg',
        },
        {
            id: 23,
            title: 'Corsair V Vengeance 32GB DDR4',
            category: 'RAM',
            brand: 'Corsair',
            price: 399,
            image: './src/img/ram/corsair-32gb.jpg',
        },
        {
            id: 24,
            title: 'Kingston Fury 8GB DDR4',
            category: 'RAM',
            brand: 'Kingston',
            price: 119,
            image: './src/img/ram/kingston-8gb.jpg',
        },
        {
            id: 25,
            title: 'Kingston Fury 16GB DDR4',
            category: 'RAM',
            brand: 'Kingston',
            price: 219,
            image: './src/img/ram/kingston-16gb.jpg',
        },
        {
            id: 26,
            title: 'Kingston Fury 32GB DDR4',
            category: 'RAM',
            brand: 'Kingston',
            price: 389,
            image: './src/img/ram/kingston-32gb.jpg',
        },
        {
            id: 27,
            title: 'Crucial 8GB DDR4',
            category: 'RAM',
            brand: 'Crucial',
            price: 109,
            image: './src/img/ram/crucial-8gb.jpg',
        },
        {
            id: 28,
            title: 'Crucial 16GB DDR4',
            category: 'RAM',
            brand: 'Crucial',
            price: 209,
            image: './src/img/ram/crucial-16gb.jpg',
        },
        {
            id: 29,
            title: 'Crucial 32GB DDR4',
            category: 'RAM',
            brand: 'Crucial',
            price: 379,
            image: './src/img/ram/crucial-32gb.jpg',
        },
        {
            id: 30,
            title: 'Samsung 16GB DDR4',
            category: 'RAM',
            brand: 'Samsung',
            price: 199,
            image: './src/img/ram/samsung-16gb.jpg',
        },

        // === SSD ===
        {
            id: 31,
            title: 'Samsung 970 EVO 250GB',
            category: 'SSD',
            brand: 'Samsung',
            price: 199,
            image: './src/img/ssd/samsung-970evo-250.jpg',
        },
        {
            id: 32,
            title: 'Samsung 970 EVO 500GB',
            category: 'SSD',
            brand: 'Samsung',
            price: 299,
            image: './src/img/ssd/samsung-970evo-500.jpg',
        },
        {
            id: 33,
            title: 'Samsung 980 PRO 1TB',
            category: 'SSD',
            brand: 'Samsung',
            price: 499,
            image: './src/img/ssd/samsung-980pro-1tb.jpg',
        },
        {
            id: 34,
            title: 'Crucial MX500 250GB',
            category: 'SSD',
            brand: 'Crucial',
            price: 159,
            image: './src/img/ssd/crucial-mx500-250.jpg',
        },
        {
            id: 35,
            title: 'Crucial MX500 500GB',
            category: 'SSD',
            brand: 'Crucial',
            price: 229,
            image: './src/img/ssd/crucial-mx500-500.jpg',
        },
        {
            id: 36,
            title: 'Crucial P5 Plus 1TB',
            category: 'SSD',
            brand: 'Crucial',
            price: 449,
            image: './src/img/ssd/crucial-p5plus-1tb.jpg',
        },
        {
            id: 37,
            title: 'Kingston A2000 250GB',
            category: 'SSD',
            brand: 'Kingston',
            price: 149,
            image: './src/img/ssd/kingston-a2000-250.jpg',
        },
        {
            id: 38,
            title: 'Kingston A2000 500GB',
            category: 'SSD',
            brand: 'Kingston',
            price: 219,
            image: './src/img/ssd/kingston-a2000-500.jpg',
        },
        {
            id: 39,
            title: 'Kingston NV2 1TB',
            category: 'SSD',
            brand: 'Kingston',
            price: 399,
            image: './src/img/ssd/kingston-nv2-1tb.jpg',
        },
        {
            id: 40,
            title: 'Corsair MP600 1TB',
            category: 'SSD',
            brand: 'Corsair',
            price: 479,
            image: './src/img/ssd/corsair-mp600-1tb.jpg',
        },

        {
            id: 41,
            title: 'Intel Core i3-10100',
            category: 'CPU',
            brand: 'Intel',
            price: 349,
            image: './src/img/cpu/intel-i3-10100.jpg',
        },
        {
            id: 42,
            title: 'AMD Ryzen 3 4100',
            category: 'CPU',
            brand: 'AMD',
            price: 329,
            image: './src/img/cpu/amd-ryzen3-4100.jpg',
        },
        {
            id: 43,
            title: 'NVIDIA GTX 1050 Ti',
            category: 'GPU',
            brand: 'NVIDIA',
            price: 699,
            image: './src/img/gpu/nvidia-gtx1050ti.jpg',
        },
        {
            id: 44,
            title: 'AMD RX 580',
            category: 'GPU',
            brand: 'AMD',
            price: 599,
            image: './src/img/gpu/amd-rx580.jpg',
        },
        {
            id: 45,
            title: 'Corsair 64GB DDR4',
            category: 'RAM',
            brand: 'Corsair',
            price: 699,
            image: './src/img/ram/corsair-64gb.jpg',
        },
        {
            id: 46,
            title: 'Samsung 870 QVO 2TB',
            category: 'SSD',
            brand: 'Samsung',
            price: 699,
            image: './src/img/ssd/samsung-870qvo-2tb.jpg',
        },
        {
            id: 47,
            title: 'Crucial P3 2TB',
            category: 'SSD',
            brand: 'Crucial',
            price: 749,
            image: './src/img/ssd/crucial-p3-2tb.jpg',
        },
        {
            id: 48,
            title: 'Kingston Fury Beast 64GB',
            category: 'RAM',
            brand: 'Kingston',
            price: 749,
            image: './src/img/ram/kingston-furybeast-64gb.jpg',
        },
        {
            id: 49,
            title: 'Corsair MP600 Pro 2TB',
            category: 'SSD',
            brand: 'Corsair',
            price: 899,
            image: './src/img/ssd/corsair-mp600pro-2tb.jpg',
        },
    ];
}
